### PR TITLE
added compression() to testem express server

### PR DESCRIPTION
**Pull request by davecombs**

### CODE REVIEW

**Comment by stefanpenner** [comment]
This LGTM, the failing tests appear to be related to electron and already red on master. The rest of the tests appear to pass correctly.

I'm going to merge this, and investigate why is trunk is red....

**Comment by stefanpenner** [comment]
Opened an issue to track the debugging: https://github.com/testem/testem/issues/1350

**Comment by davecombs** [comment]
Thanks, Stef. BTW, we tested this locally and found the savings at 84% for our test case.

**Comment by stefanpenner** [comment]
@davecombs awesome, sounds great. I am very surprised we missed this earlier. Thanks for the PR.

**Pull request merged**
