### PR TITLE
Suppressing xunit summary when using intermediate output

### PR DESCRIPTION
**Pull request by vvohra**
Fixes: #803

### CODE REVIEW

**Comment by johanneswuerbach** [comment]
Great, could you add a test for this?

**Comment by vvohra** [comment]
Added a test. Let me know if you want to change any wordings.

**Comment by vvohra** [comment]
I realized that this disabled xunit output to stdout when intermediate is enabled. The original issue said to disable xunit output when intermediate is enabled AND a `report_file` is set. 

Thoughts if the PR should be updated?

**Comment by johanneswuerbach** [comment]
I think this is fine, but maybe @rwjblue could share is use-case?

**Comment by vvohra** [comment]
Hey, this isn't implemented correctly. I messed up and forgot to unit test for the XML output, I'm getting the XML output to be "Disabled XML to stdout when intermediate output is set" when it should have the results.

**Pull request merged**
