### PR TITLE
Improve browser console log & add console.group as additional method to interrupt

### PR DESCRIPTION
**Pull request by step2yeung**
This change improves the formatting of browser console log & include `console.group` as methods to interrupt from the browser console.

Before:
```
[11:43:41 AM] not ok 1 Chrome 73.0 - [9028 ms] - Acceptance | some test name
    ---
        stack: >
                at Test.test.finish (https://localhost:4444/assets/test-support.js:118724:7)
                at https://localhost:4444/assets/test-support.js:31859:19
                at processTaskQueue (https://localhost:4444/assets/test-support.js:31221:24)
                at https://localhost:4444/assets/test-support.js:31225:8
        message: >
            Test is not isolated (async execution is extending beyond the duration of the test).
            More information has been printed to the console. Please use that information to help in debugging.


        negative: >
            false
        Log: |
            { type: 'log',
              text:
               '\'Error\\n    at Backburner._later (https://localhost:4444/assets/vendor-static.js:27205:38)\\n    at Backburner.later (https://localhost:4444/assets/vendor-static.js:27015:25)\\n    at Function.next (https://localhost:4444/assets/vendor-static.js:16043:29)\\n    at Object.testTyping (https://localhost:4444/assets/tests.js:236632:17)\'\n' }
    ...
```

After:
```
[12:42:18 PM] not ok 1 Chrome 73.0 - [9221 ms] - Acceptance | some test name
    ---
        stack: >
                at Test.test.finish (https://localhost:4444/assets/test-support.js:118724:7)
                at https://localhost:4444/assets/test-support.js:31859:19
                at processTaskQueue (https://localhost:4444/assets/test-support.js:31221:24)
                at https://localhost:4444/assets/test-support.js:31225:8
        message: >
            Test is not isolated (async execution is extending beyond the duration of the test).
            More information has been printed to the console. Please use that information to help in debugging.


        negative: >
            false
        browser log: |
            GROUP: Acceptance | some test name
            GROUP: Scheduled async
            LOG: Error
                at Backburner._later (https://localhost:4444/assets/vendor-static.js:27205:38)
                at Backburner.later (https://localhost:4444/assets/vendor-static.js:27015:25)
                at Function.next (https://localhost:4444/assets/vendor-static.js:16043:29)
                at Object.testTyping (https://localhost:4444/assets/tests.js:236632:17)
```

### CODE REVIEW

**Comment by stefanpenner** [comment]
I like the cleanup!


but, ci is unhappy:

```
C:\projects\testem\tests\ci\reporter_tests.js:415
<<<<<<< HEAD
^^
SyntaxError: Unexpected token <<
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:617:28)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at C:\projects\testem\node_modules\mocha\lib\mocha.js:231:27
    at Array.forEach (<anonymous>)
    at Mocha.loadFiles (C:\projects\testem\node_modules\mocha\lib\mocha.js:228:14)
    at Mocha.run (C:\projects\testem\node_modules\mocha\lib\mocha.js:514:10)
    at Object.<anonymous> (C:\projects\testem\node_modules\mocha\bin\_mocha:480:18)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Function.Module.runMain (module.js:694:10)
    at startup (bootstrap_node.js:204:16)
    at bootstrap_node.js:625:3
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! testem@2.14.0 testem-tests: `mocha --opts tests/mocha.opts tests/*_tests.js tests/**/*_tests.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the testem@2.14.0 testem-tests script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\appveyor\AppData\Roaming\npm-cache\_logs\2019-03-14T22_06_41_839Z-debug.log
```

**Comment by step2yeung** [comment]
Appveyor seems wonky(some tests that failed now passes after a new revision) and travis runs fine.

**Comment by step2yeung** [comment]
@stefanpenner how shall we proceed? Should I try to kick off more appveyor builds?

**Comment by stefanpenner** [comment]
Ya, please try that. 

It sounds like we may need to invest in improving the stability of our windows tests...

**Comment by step2yeung** [comment]
@stefanpenner another try and appveyor passes again.
Started #1335 to start debugging n fix appveyopr tests

**Comment by stefanpenner** [comment]
released as 2.15.0

**Pull request merged**
