### PR TITLE
Having skipped tests is ok

### PR DESCRIPTION
**Pull request by nickiaconis**
cc @step2yeung

### CODE REVIEW

**Comment by step2yeung** [comment]
Thanks Nick!

**Comment by johanneswuerbach** [comment]
Thanks, could one of you add a test for this? Seems important to not regress here.

**Comment by nickiaconis** [comment]
Good point. I've updated the tap reporter tests to include a case without failures.

**Comment by johanneswuerbach** [comment]
Thanks, :bow:

**Pull request merged**
