### PR TITLE
Fix missing test output in report file.

### LINKED ISSUE #900: Specifying `report_file` option is not working in 1.9.0
I suspect https://github.com/testem/testem/commit/b97b9c290f31608256bedbe0d67fb5b328ae6b2b is to blame, but I am not certain (haven't bisected).

The config I am using is:

```js
module.exports = {
  framework: 'qunit',
  test_page: 'tests/index.html?hidepassed',
  disable_watching: true,
  host: 'localhost.twitch.tv',
  launch_in_ci: [ 'PhantomJS' ],
  launch_in_dev: [],
  xunit_intermediate_output: true
  report_file: 'test-results/data.xml',
  reporter: 'xunit'
};
```

### PR DESCRIPTION
**Pull request by tjni**
This should help resolve #900.

### CODE REVIEW

**Comment by tjni** [comment]
The CI failure appears to be because the IE8 and IE9 tests on Saucelabs are taking longer to run. I tried running them locally to debug but haven't had any success so far.

**Comment by tjni** [comment]
Saucelabs failures should be fixed by pinning the socket.io dependency version in #909.

**Comment by johanneswuerbach** [comment]
Thanks, great job and thanks for tracking this down.

**Comment by johanneswuerbach** [comment]
https://github.com/testem/testem/pull/910 should fix the ember suite, so https://github.com/testem/testem/issues/902 is the last outstanding 1.9 issue 👏

**Pull request merged**
