### PR TITLE
Fix mocha adapter

### PR DESCRIPTION
**Pull request by stefanpenner**

### CODE REVIEW

**Comment by johanneswuerbach** [comment]
Sorry, mind explaining what this fixes?

If I run without your fix, everything is working:
```
!doctype html>
<html>
<head>
<title>Test'em</title>
<script src="/testem.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/mocha/2.3.4/mocha.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/chai/3.4.1/chai.js"></script>
<script>mocha.setup('bdd')</script>
<script src="hello.js"></script>
<script src="hello_spec.js"></script>
<script>
Testem.hookIntoTestFramework();
</script>
<link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/mocha/2.3.4/mocha.css">
</head>
<body>
<div id="mocha"></div>
<script>
mocha.run()
</script>
</body>
</html>
```

**Comment by stefanpenner** [comment]
if `<div id="mocha"></div>` is before `<script src="/testem.js"></script>` `mocha` will be the the div, which confuses the adapter selector into thinking mocha is present and ready.

**Comment by johanneswuerbach** [comment]
Thank you :bow:. I'll release another rc after https://github.com/testem/testem/pull/725 passed.

**Comment by stefanpenner** [comment]
@johanneswuerbach :)

**Pull request merged**
