### PR TITLE
Publishing new version

### PR DESCRIPTION
**Pull request by paulot**
New version release so that the debug features in the testem log get published.

### CODE REVIEW

**Comment by johanneswuerbach** [comment]
Hey @paulot, I'll try to publish a new version within this week. Sadly the unreleased chunk https://github.com/testem/testem/compare/v1.13.0...master is quite large and I need to do some further testing.

**Comment by paulot** [comment]
@johanneswuerbach Awesome to hear! It will be great to get these changes in asap. Is there any way I can help in this process?

**Comment by johanneswuerbach** [comment]
Hey, I just released `1.14.0-0`. It won't be installed by default yet, but you can force it by using `"testem": "1.14.0-0"` in your package.json.

**Comment by johanneswuerbach** [comment]
Thanks you changes have been published in testem `v1.14.0`.

**Pull request closed without merging**
