### PR TITLE
⬆️ Upgrade wireform to 0.7.2

### PR DESCRIPTION
**Pull request by Jasonlgrd**
Fixe issue https://github.com/testem/testem/issues/1481

The PR to replace Wireform to Sane is open since more years (https://github.com/testem/testem/pull/1482) and I need delete useless logs. 

image

I don't have time to finish the replacement PR :(

### CODE REVIEW

**Comment by johanneswuerbach** [comment]
Could you rebase this PR @Jasonlgrd? Otherwise happy to merge it.

**Comment by Jasonlgrd** [comment]
I have rebase it 😁
But I didn't understand why you have remove the package-lock file ?

**Comment by johanneswuerbach** [comment]
As an end-user of the library you will always get the latest dependencies matching the specified ranges and this is also what we would like to test against.

In the end there shouldn't be a difference for users of testem.

**Comment by johanneswuerbach** [comment]
Released as `testem@3.15.0`

**Pull request merged**
