### PR TITLE
UTF8 Validation TypeError

### PR DESCRIPTION
**Pull request by LoicEvenium**
Update socket-io to fix "UTF8 Validation TypeError" from ws. See https://github.com/websockets/ws/issues/1021

### CODE REVIEW

**Comment by johanneswuerbach** [comment]
@stefanpenner I’m not sure about this one as far as I know socket.io 1.6 was the last release without native dependencies and every newer release has again optional native dependencies or did our opinion regarding those changed?

**Comment by stefanpenner** [comment]
@johanneswuerbach oh! That is a good point, no our stance is the same. Thanks for catching!

**Comment by stefanpenner** [comment]
we may need to revert.

**Comment by johanneswuerbach** [comment]
Seems like the latest socket.io 2 version reverted the native dependency, will give it a try once back and then either revert or upgrade further

**Comment by johanneswuerbach** [comment]
Looks like there is one missing piece, pinged the socket.io maintainers and if we get a timely answer will either revert or upgrade https://github.com/socketio/socket.io/issues/3213

**Comment by johanneswuerbach** [comment]
New version cut and released.

**Pull request merged**
