### PR TITLE
Guard for non-JSON messages on the client

### LINKED ISSUE #1156: Add extra message validation on client
Currently, the Testem client script does not validate message events, but [blindly tries to parse them into JSON](https://github.com/testem/testem/blob/241b1e42e96cd7e4d656efda6475e96e1f7978ae/public/testem/testem_connection.js#L47). This can cause issues such as those reported in https://github.com/ember-cli/ember-cli/issues/6723#issuecomment-286299900 when the data is not a JSON string.

### PR DESCRIPTION
**Pull request by trentmwillis**
Fixes #1156

### CODE REVIEW

**Comment by johanneswuerbach** [comment]
Could you log the malformed message in this case? I guess that would simplify debugging.

**Comment by trentmwillis** [comment]
For sure, will update later. I was unsure whether such a feature would be helpful.

**Comment by johanneswuerbach** [comment]
@trentmwillis any chance to add the 'console.error' here? I would like to cut a release soon and would be great to include this

**Comment by trentmwillis** [comment]
@johanneswuerbach updated! Sorry for the delay.

**Comment by johanneswuerbach** [comment]
No problem, thank you for your contribution. :-)

**Pull request merged**
