### PR TITLE
Use etags on assets request header to leverage browser cache

### PR DESCRIPTION
**Pull request by step2yeung**
handles #1280

### CODE REVIEW

**Comment by step2yeung** [comment]
Tested manually using an ember app: 
```
ember exam --server
first load of assets should be 200 response
refresh test page
consecutive loads of assets should be 304 response
change a file
reload of the change file should be 200 response
other files should be 304 response
```

**Comment by stefanpenner** [comment]
@step2yeung testing this locally, I believe it requires an additional change:

```
diff --git a/lib/server/index.js b/lib/server/index.js
index 49eea8a..0341ff1 100644
--- a/lib/server/index.js
+++ b/lib/server/index.js
@@ -235,8 +235,7 @@ class Server extends EventEmitter {
   }

   renderDefaultTestPage(req, res) {
-    res.header('Cache-Control', 'No-cache');
-    res.header('Pragma', 'No-cache');
+    app.set('etag', 'strong');
```

**Comment by stefanpenner** [comment]
@step2yeung with my above change, everything does seem to work correct. If you can make that correction, tidy up the commit history, I can merge and release this afternoon :)

**Comment by stefanpenner** [comment]
Actually, more specifically. It seems like we should:

* remove all per request caching
* add ` app.set('etag', 'strong');` where the express app is created

**Comment by stefanpenner** [comment]
I'm not sure what is up, https://github.com/testem/testem/pull/1297#issuecomment-422162984 appears to be invalid this issue just stopped happening?

**Comment by stefanpenner** [comment]
released as v2.12.0 🎉

**Pull request merged**
