### PR TITLE
fixes #1419 implement failed tests count in summary output

### LINKED ISSUE #1419: [dot_reporter] Show counter of failed tests in summary
It might be helpful to include the information about failed tests count into the summary output
`node_modules/testem/lib/reporters/dot_reporter.js`

### PR DESCRIPTION
**Pull request by Mifrill**
closes #1419

### CODE REVIEW

**Comment by Mifrill** [comment]
locally the all tests passed with the integration tests, probably it's something not related to the current code changes
```
npm run integration
echo $?
=> 0
```

**Comment by johanneswuerbach** [comment]
@Mifrill could you rebase your branch? The tests are fixed in the latest master.

**Comment by Mifrill** [comment]
is it better to probably use the same approach as for TapReporter?:
```
// testem/lib/reporters/tap_reporter.js
summaryDisplay() {
    let lines = [
      `1..${  this.total}`,
      `# tests ${  this.total}`,
      `# pass  ${  this.pass}`,
      `# skip  ${  this.skipped}`,
      `# fail  ${  this.total - this.pass - this.skipped}`
    ];

    if (this.pass + this.skipped === this.total) {
      lines.push('');
      lines.push('# ok');
    }

    return lines.join('\n');
  }
```

**Comment by johanneswuerbach** [comment]
Yes, if you could do this change, it would probably be better to keep them consitent.

**Comment by Mifrill** [comment]
@johanneswuerbach thank you!

**Comment by johanneswuerbach** [comment]
Released as https://github.com/testem/testem/releases/tag/v3.3.0, thank you 👏

**Pull request merged**
