### PR TITLE
Adding headless chrome to known browser

### PR DESCRIPTION
**Pull request by step2yeung**
addresses #1291

### CODE REVIEW

**Comment by step2yeung** [comment]
@stefanpenner Mind taking a look?

**Comment by stefanpenner** [comment]
@step2yeung LGTM. Should I cut a release?

**Comment by step2yeung** [comment]
@stefanpenner mind cutting a release with https://github.com/testem/testem/pull/1295

**Comment by stefanpenner** [comment]
released as v2.11.0 🎉

**Pull request merged**
