### PR TITLE
Wrap Google Chrome with dbus-launch

### PR DESCRIPTION
**Pull request by davidhao3300**
As discussed here: https://github.com/testem/testem/issues/772
I'm not sure how to test for any regressions given that tests appear to be run through mocha and not through any browsers.

### CODE REVIEW

**Comment by johanneswuerbach** [comment]
I still don't think this should be part of testem and instead `dbus-launch --exit-with-session testem` should be used. Wouldn't this work?

The reason I tend more to :-1: is that can we be sure that every Linux having `dbus-launch` can wrap chrome like this? What if people using testem in a existing GUI session?

**Comment by davidhao3300** [comment]
Yeah, I'm hoping someone with a Linux browser/anyone who's had problems could speak up.

**Comment by davidhao3300** [comment]
The solution you suggested should work for us, so this PR isn't really critical

**Comment by davidhao3300** [comment]
Maybe better would be to just add something to the docs regarding this issue?

**Comment by johanneswuerbach** [comment]
Yep, I would prefer this. For the current change I just am not able to predict whether this might break anybody or not :cry: .

**Comment by johanneswuerbach** [comment]
Any update on this?

**Comment by davidhao3300** [comment]
I'll add the docs some time next week, have final exams lol

**Comment by johanneswuerbach** [comment]
No worries and good luck with your finals! :-)

**Comment by manish-northout** [comment]
still chromium and chrome are not working through.could you please have a look guys.because locally when i run the test-case its working in Ubuntu 16.04.

**Comment by johanneswuerbach** [comment]
Could you create a new issue with also including additional details about your config and environment? Without this, this is hardly actionable and likely forgotten

**Pull request closed without merging**
